
all:
	$(MAKE) -C arithmetic
	$(MAKE) -C assertions
	$(MAKE) -C attributes
	$(MAKE) -C initialization
	$(MAKE) -C local_vars
	$(MAKE) -C null_dereference
	$(MAKE) -C resource_leaks
	$(MAKE) -C memory_leaks
	$(MAKE) -C lists
	$(MAKE) -C dangling_deref

clean:
	$(MAKE) -C arithmetic clean
	$(MAKE) -C assertions clean
	$(MAKE) -C attributes clean
	$(MAKE) -C initialization clean
	$(MAKE) -C local_vars clean
	$(MAKE) -C null_dereference clean
	$(MAKE) -C resource_leaks clean
	$(MAKE) -C memory_leaks
	$(MAKE) -C lists
	$(MAKE) -C dangling_deref

